### ISSUE TITLE
"orstationc" dataset is missing

### ISSUE THREAD

**Issue by mdozmorov** [geanders/RProgrammingForResearch#34]
The `12-reportingresults3.Rmd` file reads the data from the web: 
````
orstationc <- read.csv(paste0("http://geog.uoregon.edu/bartlein/",
                              "old_courses/geog414s05/data/orstationc.csv"))
````
The link is broken. Would it be possible to include this CSV in the repo?

Thanks for the very useful material.
Mikhail

**Comment by geanders** [comment]
Thanks, @mdozmorov! I've added the csv directly in the data subdirectory.
